CONFIG_RUST=y
CONFIG_RUST_ALLOC=y

CONFIG_MAIN_STACK_SIZE=65536
CONFIG_HEAP_MEM_POOL_SIZE=3145728

CONFIG_POSIX_API=y
CONFIG_POSIX_THREAD_THREADS_MAX=8
CONFIG_MAX_PTHREAD_MUTEX_COUNT=16
CONFIG_MAX_PTHREAD_COND_COUNT=16
CONFIG_POSIX_THREAD_ATTR_STACKSIZE=y

CONFIG_LOG=y
CONFIG_LOG_BACKEND_RTT=n
